/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentsDocumentIdRouteImport } from './routes/documents.$documentId'
import { Route as DocumentsNewRouteImport } from './routes/documents.new'
import { Route as PlantillasCierreRouteImport } from './routes/plantillas.cierre'
import { Route as PlantillasInicioRouteImport } from './routes/plantillas.inicio'
import { Route as DocumentsDocumentIdIndexRouteImport } from './routes/documents.$documentId.index'
import { Route as DocumentsDocumentIdEditRouteImport } from './routes/documents.$documentId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsDocumentIdRoute = DocumentsDocumentIdRouteImport.update({
  id: '/documents/$documentId',
  path: '/documents/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsNewRoute = DocumentsNewRouteImport.update({
  id: '/documents/new',
  path: '/documents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantillasCierreRoute = PlantillasCierreRouteImport.update({
  id: '/plantillas/cierre',
  path: '/plantillas/cierre',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantillasInicioRoute = PlantillasInicioRouteImport.update({
  id: '/plantillas/inicio',
  path: '/plantillas/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsDocumentIdIndexRoute =
  DocumentsDocumentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DocumentsDocumentIdRoute,
  } as any)
const DocumentsDocumentIdEditRoute = DocumentsDocumentIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DocumentsDocumentIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRouteWithChildren
  '/documents/new': typeof DocumentsNewRoute
  '/plantillas/cierre': typeof PlantillasCierreRoute
  '/plantillas/inicio': typeof PlantillasInicioRoute
  '/documents/$documentId/edit': typeof DocumentsDocumentIdEditRoute
  '/documents/$documentId/': typeof DocumentsDocumentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documents/new': typeof DocumentsNewRoute
  '/plantillas/cierre': typeof PlantillasCierreRoute
  '/plantillas/inicio': typeof PlantillasInicioRoute
  '/documents/$documentId/edit': typeof DocumentsDocumentIdEditRoute
  '/documents/$documentId': typeof DocumentsDocumentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRouteWithChildren
  '/documents/new': typeof DocumentsNewRoute
  '/plantillas/cierre': typeof PlantillasCierreRoute
  '/plantillas/inicio': typeof PlantillasInicioRoute
  '/documents/$documentId/edit': typeof DocumentsDocumentIdEditRoute
  '/documents/$documentId/': typeof DocumentsDocumentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documents/$documentId'
    | '/documents/new'
    | '/plantillas/cierre'
    | '/plantillas/inicio'
    | '/documents/$documentId/edit'
    | '/documents/$documentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/documents/new'
    | '/plantillas/cierre'
    | '/plantillas/inicio'
    | '/documents/$documentId/edit'
    | '/documents/$documentId'
  id:
    | '__root__'
    | '/'
    | '/documents/$documentId'
    | '/documents/new'
    | '/plantillas/cierre'
    | '/plantillas/inicio'
    | '/documents/$documentId/edit'
    | '/documents/$documentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocumentsDocumentIdRoute: typeof DocumentsDocumentIdRouteWithChildren
  DocumentsNewRoute: typeof DocumentsNewRoute
  PlantillasCierreRoute: typeof PlantillasCierreRoute
  PlantillasInicioRoute: typeof PlantillasInicioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$documentId': {
      id: '/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof DocumentsDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/new': {
      id: '/documents/new'
      path: '/documents/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof DocumentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plantillas/cierre': {
      id: '/plantillas/cierre'
      path: '/plantillas/cierre'
      fullPath: '/plantillas/cierre'
      preLoaderRoute: typeof PlantillasCierreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plantillas/inicio': {
      id: '/plantillas/inicio'
      path: '/plantillas/inicio'
      fullPath: '/plantillas/inicio'
      preLoaderRoute: typeof PlantillasInicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$documentId/': {
      id: '/documents/$documentId/'
      path: '/'
      fullPath: '/documents/$documentId/'
      preLoaderRoute: typeof DocumentsDocumentIdIndexRouteImport
      parentRoute: typeof DocumentsDocumentIdRoute
    }
    '/documents/$documentId/edit': {
      id: '/documents/$documentId/edit'
      path: '/edit'
      fullPath: '/documents/$documentId/edit'
      preLoaderRoute: typeof DocumentsDocumentIdEditRouteImport
      parentRoute: typeof DocumentsDocumentIdRoute
    }
  }
}

interface DocumentsDocumentIdRouteChildren {
  DocumentsDocumentIdEditRoute: typeof DocumentsDocumentIdEditRoute
  DocumentsDocumentIdIndexRoute: typeof DocumentsDocumentIdIndexRoute
}

const DocumentsDocumentIdRouteChildren: DocumentsDocumentIdRouteChildren = {
  DocumentsDocumentIdEditRoute: DocumentsDocumentIdEditRoute,
  DocumentsDocumentIdIndexRoute: DocumentsDocumentIdIndexRoute,
}

const DocumentsDocumentIdRouteWithChildren =
  DocumentsDocumentIdRoute._addFileChildren(DocumentsDocumentIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocumentsDocumentIdRoute: DocumentsDocumentIdRouteWithChildren,
  DocumentsNewRoute: DocumentsNewRoute,
  PlantillasCierreRoute: PlantillasCierreRoute,
  PlantillasInicioRoute: PlantillasInicioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
